export const skills = [
  {
    skillName: 'React',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/react/react-original-wordmark.svg',
    skillAlt: 'React Logo',
    skillDoc: 'https://react.dev/reference/react',
  },
  {
    skillName: 'React Router',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/reactrouter/reactrouter-original-wordmark.svg',
    skillAlt: 'React Router Logo',
    skillDoc: 'https://reactrouter.com/homeam',
  },
  {
    skillName: 'Redux',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/redux/redux-original.svg',
    skillAlt: 'Redux Logo',
    skillDoc: 'https://redux.js.org/introduction/getting-started',
  },
  {
    skillName: 'Vue.js',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/vuejs/vuejs-original-wordmark.svg',
    skillAlt: 'Vue.js Logo',
    skillDoc: 'https://vuejs.org/guide/introduction.html',
  },
  {
    skillName: 'Nuxt',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nuxt/nuxt-original-wordmark.svg',
    skillAlt: 'Nuxt Logo',
    skillDoc: 'https://nuxt.com/docs/4.x/getting-started/introductionred',
  },
  {
    skillName: 'expressJS',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/express/express-original-wordmark.svg',
    skillAlt: 'Express JS Logo',
    skillDoc: 'https://expressjs.com/en/5x/starter/installing/',
  },
  {
    skillName: 'jQuery',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/jquery/jquery-original-wordmark.svg',
    skillAlt: 'jQuery Logo',
    skillDoc: 'https://api.jquery.com/',
  },
  {
    skillName: 'TypeScript',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/typescript/typescript-original.svg',
    skillAlt: 'TypeScript Logo',
    skillDoc: 'https://www.typescriptlang.org/docs/',
  },
  {
    skillName: 'JavaScript',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/javascript/javascript-original.svg',
    skillAlt: 'JavaScript Logo',
    skillDoc: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
  },
  {
    skillName: 'NodeJS',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nodejs/nodejs-original-wordmark.svg',
    skillAlt: 'NodeJS Logo',
    skillDoc: 'https://beta.docs.nodejs.org/',
  },
  {
    skillName: 'Python',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/python/python-original-wordmark.svg',
    skillAlt: 'Python Logo',
    skillDoc: 'https://docs.python.org/3/',
  },
  {
    skillName: 'PHP',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/php/php-original.svg',
    skillAlt: 'PHP logo',
    skillDoc: 'https://www.php.net/manual/en/',
  },
  {
    skillName: 'C++',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/cplusplus/cplusplus-original.svg',
    skillAlt: 'C++ Logo',
    skillDoc: 'https://devdocs.io/cpp/',
  },
  {
    skillName: 'MongoDB',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/mongodb/mongodb-plain-wordmark.svg',
    skillAlt: 'MongoDB Logo',
    skillDoc: 'https://www.mongodb.com/docs/',
  },
  {
    skillName: 'PostgreSQL',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/postgresql/postgresql-original-wordmark.svg',
    skillAlt: 'PostgreSQL Logo',
    skillDoc: 'https://www.postgresql.org/docs/',
  },
  {
    skillName: 'HTML5',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/html5/html5-original-wordmark.svg',
    skillAlt: 'HTML5 Logo',
    skillDoc: 'https://developer.mozilla.org/en-US/docs/Web/HTML',
  },
  {
    skillName: 'CSS3',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/css3/css3-original-wordmark.svg',
    skillAlt: 'CSS3 Logo',
    skillDoc: 'https://developer.mozilla.org/en-US/docs/Web/CSS',
  },
  {
    skillName: 'MarkDown',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/markdown/markdown-original.svg',
    skillAlt: 'MarkDown Logo',
    skillDoc: 'https://www.markdownguide.org/getting-started/',
  },

  {
    skillName: 'Git',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/git/git-original-wordmark.svg',
    skillAlt: 'Git Logo',
    skillDoc: 'https://git-scm.com/docs',
  },
  {
    skillName: 'Github',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/github/github-original-wordmark.svg',
    skillAlt: 'Github Logo',
    skillDoc: 'https://docs.github.com/en',
  },
  {
    skillName: 'Amazon Web Services',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/amazonwebservices/amazonwebservices-original-wordmark.svg',
    skillAlt: 'Amazon Web Services Logo',
    skillDoc: 'https://docs.aws.amazon.com/?nc2=h_rsc_lrn_docs',
  },
  {
    skillName: 'NPM',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/npm/npm-original-wordmark.svg',
    skillAlt: 'NPM logo',
    skillDoc: 'https://docs.npmjs.com/',
  },
  {
    skillName: 'Vite',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/vitejs/vitejs-original.svg',
    skillAlt: 'Vite Logo',
    skillDoc: 'https://vite.dev/guide/',
  },
  {
    skillName: 'Tailwind CSS',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/tailwindcss/tailwindcss-original.svg',
    skillAlt: 'Tailwind CSS Logo',
    skillDoc: 'https://tailwindcss.com/docs/styling-with-utility-classesnpm ',
  },
  {
    skillName: 'Sass',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/sass/sass-original.svg',
    skillAlt: 'Sass Logo',
    skillDoc: 'https://sass-lang.com/documentation/',
  },
  {
    skillName: 'Netlify',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/netlify/netlify-original-wordmark.svg',
    skillAlt: 'Netlify Logo',
    skillDoc: 'https://docs.netlify.com/',
  },
  {
    skillName: 'Jenkins',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/jenkins/jenkins-original.svg',
    skillAlt: 'Jenkins Logo',
    skillDoc: 'https://www.jenkins.io/doc/book/',
  },
  {
    skillName: 'Postman',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/postman/postman-original.svg',
    skillAlt: 'Postman Logo',
    skillDoc: 'https://learning.postman.com/',
  },
  {
    skillName: 'New Relic',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/newrelic/newrelic-original.svg',
    skillAlt: 'New Relic Logo',
    skillDoc: 'https://docs.newrelic.com/',
  },
  {
    skillName: 'Jira',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/jira/jira-original-wordmark.svg',
    skillAlt: 'Jira Logo',
    skillDoc: 'https://confluence.atlassian.com/jira',
  },
  {
    skillName: 'Confluence',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/confluence/confluence-original-wordmark.svg',
    skillAlt: 'Confluence Logo',
    skillDoc: 'https://confluence.atlassian.com/alldoc/confluence-documentation-directory-12877996.html',
  },
  {
    skillName: 'Visual Studio Code',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/vscode/vscode-original-wordmark.svg',
    skillAlt: 'Visual Studio Code Logo',
    skillDoc: 'https://code.visualstudio.com/docs',
  },
  {
    skillName: 'Slack',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/slack/slack-original-wordmark.svg',
    skillAlt: 'Slack Logo',
    skillDoc: 'https://docs.slack.dev/',
  },
  {
    skillName: 'Figma',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/figma/figma-original.svg',
    skillAlt: 'Figma Logo',
    skillDoc: 'https://help.figma.com/hc/en-us/categories/360002051613-Get-startedlin',
  },
  {
    skillName: 'Linux',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/linux/linux-original.svg',
    skillAlt: 'Linux Logo',
    skillDoc: 'https://docs.kernel.org/',
  },
  {
    skillName: 'Ubuntu',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/ubuntu/ubuntu-original-wordmark.svg',
    skillAlt: 'Ubuntu Logo',
    skillDoc: 'https://ubuntu.com/desktop/docs/en/latest/',
  },
  {
    skillName: 'Apple',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/apple/apple-original.svg',
    skillAlt: 'Apple Logo',
    skillDoc: 'https://developer.apple.com/documentationwi',
  },
  {
    skillName: 'Windows 11',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/windows11/windows11-original-wordmark.svg',
    skillAlt: 'Windows 11 Logo',
    skillDoc: 'https://learn.microsoft.com/en-us/windows/',
  },
  {
    skillName: 'zsh',
    skillLink: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/zsh/zsh-original-wordmark.svg',
    skillAlt: 'zshell Logo',
    skillDoc: 'https://zsh.sourceforge.io/Doc/Release/zsh_toc.html',
  },
];
